git_repo: git@github.com:1919teja/ML-webapp-dashboards.git
git_root_dir_build: /Users/kottapallysaiteja/Autmation/ML-webapp-dashboards
git_tmp: /Users/kottapallysaiteja/Autmation/tmp
git_key_path: /Users/kottapallysaiteja/.ssh/git.rsa
