---
- name: git-checkout
  hosts: localhost
  become: no
  tasks:
  #---------------------- Git Checkout -----------------------------------------
      - name: Step - Git checkout {{git_version}}
        tags: git_checkout
        environment:
          TMPDIR: "{{git_tmp}}"
        git:
          repo: "{{git_repo}}"
          dest: "{{git_root_dir_build}}"
          force: yes
          accept_hostkey: yes
          clone: no
          key_file: "{{git_key_path}}"
          version: "{{git_version}}"